const REWRITE_ASSISTANT_TOKEN_COST = 1;
const AI_CONTENT_GENERATION_TOKEN_COST = 10;

const DOCUMENT_NAME_RULES = {
  MIN: 1,
  MAX: 70,
} as const;

export {
  REWRITE_ASSISTANT_TOKEN_COST,
  AI_CONTENT_GENERATION_TOKEN_COST,
  DOCUMENT_NAME_RULES,
};
