name: Commitlint and Commit Count Check

on:
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Commit Count Check
        run: |
          BASE_BRANCH=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r .base.ref)
          commit_count=$(git rev-list --count "$BASE_BRANCH..HEAD")
          if [ "$commit_count" -ne 1 ]; then
            echo "Error: The number of commits in the pull request must be exactly 1."
            exit 1
          fi

      - name: Run Commitlint
        run: |
          BASE_BRANCH=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r .base.ref)
          git diff --name-only "$BASE_BRANCH..HEAD" | xargs -I {} npx commitlint --edit "{}"
