name: Check Outdated Packages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-outdated-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Check for outdated packages
        run: |
          OUTDATED=$(npm outdated --json)
          echo $OUTDATED | jq .
          if [ "$OUTDATED" != "{}" ]; then
            echo "Error: Some packages are outdated."
            exit 1
          else
            echo "All packages are up to date."
          fi
        shell: bash
