name: Check for Outdated Dependencies

on:
  pull_request:
    branches: ['develop']

jobs:
  check-outdated-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: Check outdated dependencies with ncu
        run: |
          ncu --json > outdated-deps.json

          OUTDATED_DEPS=$(cat outdated-deps.json)

          if [ "$OUTDATED_DEPS" = "{}" ]; then
            echo "No outdated dependencies found."
          else
            echo "Outdated dependencies:"
            echo "$OUTDATED_DEPS"
          fi
