name: Outdated Dependencies

on:
  pull_request:
    branches: ['develop']

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: Log All Dependencies
        run: ncu

      - name: Check for Breaking Changes
        id: ncu_check
        run: |
          ncu --jsonUpgraded > ncu-result.json
          MAJOR_UPDATES=$(jq 'to_entries[] | select(.value | contains("major")) | .key' ncu-result.json)
          if [ -n "$MAJOR_UPDATES" ]; then
            echo "Breaking changes detected in the following dependencies: $MAJOR_UPDATES"
            exit 1
          fi

      - name: Handle Breaking Changes
        if: ${{ steps.ncu_check.outcome == 'failure' }}
        run: |
          echo "Breaking changes detected. Please update the dependencies in a separate branch."
          exit 1
