name: Check for Outdated Dependencies

on:
  pull_request:
    branches: ['develop']

jobs:
  check-outdated-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Check outdated dependencies
        run: |
          npm outdated --json > outdated-deps.json || true

          OUTDATED_DEPS=$(cat outdated-deps.json)

          if [ -z "$OUTDATED_DEPS" ]; then
            echo "No outdated dependencies found."
          else
            echo "Outdated dependencies:"
            echo "$OUTDATED_DEPS"
          fi
