name: Linting

on:
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          npm-version-file: 'package.json'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run Linting
        run: npm run ci:lint
