name: Type Check

on:
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run Type Checking
        run: npm run typecheck
